version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8000:80"
    environment:
      - APP_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./react-veiw
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-veiw:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 